//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Address.View.WCFAddress {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFAddress.IAddressService")]
    public interface IAddressService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressService/Address_Add", ReplyAction="http://tempuri.org/IAddressService/Address_AddResponse")]
        bool Address_Add(Address.Business.Entities.Address address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressService/Address_RestoreFromHistory", ReplyAction="http://tempuri.org/IAddressService/Address_RestoreFromHistoryResponse")]
        bool Address_RestoreFromHistory(string H_ID, string UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressService/Address_GetDetailWithChildren", ReplyAction="http://tempuri.org/IAddressService/Address_GetDetailWithChildrenResponse")]
        Address.Business.Entities.Address Address_GetDetailWithChildren(string AddressID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressService/Address_GetDetailWithHistory", ReplyAction="http://tempuri.org/IAddressService/Address_GetDetailWithHistoryResponse")]
        Address.Business.Entities.Address Address_GetDetailWithHistory(string AddressID, string UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressService/Address_Review", ReplyAction="http://tempuri.org/IAddressService/Address_ReviewResponse")]
        bool Address_Review(string AddressID, string UserID, int Status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressService/History_AddAddress", ReplyAction="http://tempuri.org/IAddressService/History_AddAddressResponse")]
        bool History_AddAddress(Address.Business.Entities.History history);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressService/History_Update", ReplyAction="http://tempuri.org/IAddressService/History_UpdateResponse")]
        bool History_Update(Address.Business.Entities.History history);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressService/History_GetAddressOfUser", ReplyAction="http://tempuri.org/IAddressService/History_GetAddressOfUserResponse")]
        Address.Business.Entities.History[] History_GetAddressOfUser(string UserID, int PageNumber, int ItemPerPage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressService/History_GetDetail", ReplyAction="http://tempuri.org/IAddressService/History_GetDetailResponse")]
        Address.Business.Entities.History History_GetDetail(string H_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressService/User_Add", ReplyAction="http://tempuri.org/IAddressService/User_AddResponse")]
        bool User_Add(Address.Business.Entities.User user);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAddressServiceChannel : Address.View.WCFAddress.IAddressService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AddressServiceClient : System.ServiceModel.ClientBase<Address.View.WCFAddress.IAddressService>, Address.View.WCFAddress.IAddressService {
        
        public AddressServiceClient() {
        }
        
        public AddressServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AddressServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AddressServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AddressServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Address_Add(Address.Business.Entities.Address address) {
            return base.Channel.Address_Add(address);
        }
        
        public bool Address_RestoreFromHistory(string H_ID, string UserID) {
            return base.Channel.Address_RestoreFromHistory(H_ID, UserID);
        }
        
        public Address.Business.Entities.Address Address_GetDetailWithChildren(string AddressID) {
            return base.Channel.Address_GetDetailWithChildren(AddressID);
        }
        
        public Address.Business.Entities.Address Address_GetDetailWithHistory(string AddressID, string UserID) {
            return base.Channel.Address_GetDetailWithHistory(AddressID, UserID);
        }
        
        public bool Address_Review(string AddressID, string UserID, int Status) {
            return base.Channel.Address_Review(AddressID, UserID, Status);
        }
        
        public bool History_AddAddress(Address.Business.Entities.History history) {
            return base.Channel.History_AddAddress(history);
        }
        
        public bool History_Update(Address.Business.Entities.History history) {
            return base.Channel.History_Update(history);
        }
        
        public Address.Business.Entities.History[] History_GetAddressOfUser(string UserID, int PageNumber, int ItemPerPage) {
            return base.Channel.History_GetAddressOfUser(UserID, PageNumber, ItemPerPage);
        }
        
        public Address.Business.Entities.History History_GetDetail(string H_ID) {
            return base.Channel.History_GetDetail(H_ID);
        }
        
        public bool User_Add(Address.Business.Entities.User user) {
            return base.Channel.User_Add(user);
        }
    }
}
